name: Khushboo Dhiman
url: http://matt.harzewski.com
description: Insert tagline here

permalink: /jekyllthemes/

plugins: [jekyll-paginate]

highlighter: pygments
paginate: 20
theme: Kross-Creative-Portfolio-Theme

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
